name: AderynDawn
favicon: null
layout_spectrum: 0.8298216939438134
typography_spectrum: 0.8439771747216582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.892411996377632
  lightness: 0.38949601631611586
  saturation: 0.8556970318313688
  rhythmicContrast: 0.060338056180626154
purpose: []
