name: AderynDawn
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48757
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040507'
    - '#dbe0e4'
    - '#30424e'
    - '#748795'
  brandStrength: 0.892411996377632
  lightness: 0.38949601631611586
  saturation: 0.8556970318313688
  rhythmicContrast: 0.060338056180626154
purpose: []
