name: AderynDawn
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6344086
  brandStrength: 0.2992831
  lightness: 0.4318996
  brandColors:
    - '#ffffff'
    - '#040507'
    - '#dbe0e4'
    - '#30424e'
    - '#748795'
  rhythmicContrast: 1
typography_spectrum: 0.48757
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
